from dotenv import load_dotenv
load_dotenv()

from langchain_core.output_parsers import CommaSeparatedListOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq

# Initialize the parser
output_parser = CommaSeparatedListOutputParser()

# Create a prompt template
# We inject the format instructions automatically generated by the parser
prompt = PromptTemplate(
    template="List five {subject}.\n{format_instructions}",
    input_variables=["subject"],
    partial_variables={"format_instructions": output_parser.get_format_instructions()}
)

# Initialize the LLM
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

# Create a chain combining the prompt, llm, and output parser
chain = prompt | llm | output_parser

# Invoke the chain
result = chain.invoke({"subject": "popular car brands"})

print("Parsed Result:")
print(result)
print(f"\nType of result: {type(result)}")

print("\nIterating over list:")
for i, item in enumerate(result):
    print(f"Item {i+1}: {item}")
